language: generic
sudo: required #root permission to install docker
services:
    - docker #installs copy of docker 

before_install:
    - docker build -t osama85/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true osama85/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: "$ACCESS_ID"
    secret_access_key: "$SECRET_ID"
    aws_session_token: "$SESSION_TOKEN"
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-243950353262"
    bucket_path: "docker-react"
    on:
        branch: master


    
