language: generic
sudo: required #root permission to install docker
services:
    - docker #installs copy of docker 

before_install:
    - docker build -t osama85/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true osama85/docker-react npm run test -- --coverage
